version: '3.8'

services:
  # -------------------------
  # 1. BANCO DE DADOS (MySQL)
  # -------------------------
  mysql:
    image: mysql:8.0
    container_name: linkonfood_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------------
  # 2. OBSERVABILIDADE (ELASTIC STACK)
  # ----------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24  
    container_name: elasticsearch_server
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.24
    container_name: apm_server
    ports:
      - "8200:8200"
    command: >
      apm-server -e
      -E output.elasticsearch.hosts=["elasticsearch:9200"]
      -E apm-server.host="0.0.0.0:8200"
      -E apm-server.rpt.enabled=false
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.24  
    container_name: kibana_dashboard
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  # ----------------------
  # 3. MICROSSERVIÇOS JAVA
  # ----------------------
  
  # Discovery Server (Eureka Server)
  server:
    build: ./server
    container_name: eureka_server
    ports:
      - "8081:8081"
    depends_on:
      - apm-server
    environment:
      - SERVER_PORT=8081 
      - ELASTIC_APM_SERVICE_NAME=eureka-server
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - ELASTIC_APM_ENVIRONMENT=development

  # Microsserviço de Pedidos
  pedidos:
    build: ./pedidos
    depends_on:
      mysql:
        condition: service_healthy
      server:
        condition: service_started
    environment:
      - SERVER_PORT=8086 
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:3306/linkonfood-pedidos?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - EUREKA_SERVER=server
      - DB_HOST=${DB_HOST}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://server:8081/eureka/
      - ELASTIC_APM_SERVICE_NAME=ms-pedidos
      - JAVA_TOOL_OPTIONS=-Delastic.apm.server_url=http://apm-server:8200 -Delastic.apm.service_name=ms-pedidos -Delastic.apm.environment=development  
      - ELASTIC_APM_ENVIRONMENT=development

  # Microsserviço de Pagamentos
  pagamentos:
    build: ./pagamentos
    depends_on:
      mysql:
        condition: service_healthy
      server:
        condition: service_started
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:3306/linkonfood-pagamentos?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - EUREKA_SERVER=server
      - DB_HOST=${DB_HOST}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://server:8081/eureka/
      - ELASTIC_APM_SERVICE_NAME=ms-pagamentos
      - JAVA_TOOL_OPTIONS=-Delastic.apm.server_url=http://apm-server:8200 -Delastic.apm.service_name=ms-pagamentos -Delastic.apm.environment=development  
      - ELASTIC_APM_ENVIRONMENT=development

  # API Gateway
  gateway:
    build: ./gateway
    container_name: api_gateway
    ports:
      - "8082:8082"
    depends_on:
      server:
        condition: service_started
    environment:
      - SERVER_PORT=8082 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://server:8081/eureka/
      - ELASTIC_APM_SERVICE_NAME=api-gateway
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - JAVA_TOOL_OPTIONS=-Delastic.apm.server_url=http://apm-server:8200 -Delastic.apm.service_name=ms-pedidos -Delastic.apm.environment=development  
      - ELASTIC_APM_ENVIRONMENT=development
