
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql}:3306/linkonfood-pagamento?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=true


spring.application.name=pagamentos-ms
server.port=${SERVER_PORT:8085}
eureka.client.serviceUrl.defaultZone=http://${EUREKA_SERVER:server}:8081/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.uuid}


spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false

resilience4j.circuitbreaker.instances.atualizaPedido.sliding-window-size= 3
resilience4j.circuitbreaker.instances.atualizaPedido.minimum-number-of-calls= 2
resilience4j.circuitbreaker.instances.atualizaPedido.wait-duration-in-open-state= 50s

eureka.instance.prefer-ip-address=true

eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

