name: "2. Application Deploy (Docker)"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  deploy_app:
    name: "Build & Deploy Services"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      # Inicializa o terraform para CONSULTAR os outputs (IP e RDS)
      - name: Fetch Infrastructure Details
        id: infra_info
        run: |
          terraform init
          echo "RDS_HOST=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Get GitHub Actions Runner IP
        id: get_ip
        run: echo "ip=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Open SSH port for GitHub Runner
        run: |
          SG_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=linkonfood-ec2-sg" --query "SecurityGroups[0].GroupId" --output text)
          echo "SG_ID=$SG_ID" >> $GITHUB_ENV
          aws ec2 authorize-security-group-ingress --group-id $SG_ID --protocol tcp --port 22 --cidr ${{ steps.get_ip.outputs.ip }}/32

      - name: Copy Files to EC2 via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/home/ubuntu/app"

      - name: Deploy Containers on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app
            echo "DB_HOST=${{ env.RDS_HOST }}" > .env
            echo "DB_USERNAME=root" >> .env
            echo "DB_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
            
            docker compose down
            docker compose up -d --build

      - name: Close SSH port (Clean up)
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ env.SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.get_ip.outputs.ip }}/32
